package:
  name: pyocct
  version: "0.0.1"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - vc 14 # [win]
    - cmake
    - ninja
    - pybind11
    - occt 7.2.0
    - smesh 8.3.0
    - netgen4smesh 6.2.0

  run:
    - vc 14 # [win]
    - occt 7.2.0
    - smesh 8.3.0
    - netgen4smesh 6.2.0

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
