context:
    version: 7.9.1
package:
  name: pyocct
  version: '{{version}}'

source:
  path: ../

build:
  number: 100

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - sel(win): '{{ compiler("cxx") }}'
    - sel(win): glew
    - cmake
    - ninja
    - rapidjson
    - python
    - setuptools

  host:
    - python
    - pybind11
    - setuptools
    - occt =={{version}}=*novtk*
    - sel(linux): '{{ cdt("libxi-devel") }}'
    - sel(linux): '{{ cdt("libxext-devel") }}'
    - sel(linux): libegl-devel
    - sel(linux): libopengl-devel
    - sel(linux): wayland

  run:
    - python
    - occt =={{version}}=*novtk*

test:
  source_files:
    - test

about:
  home: https://github.com/trelau/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE.
  description: Python bindings for OpenCASCADE geometry kernel.

